name: langchain-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
    - streamlit>=1.28.0
    - requests>=2.31.0
    - python-dotenv>=1.0.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - langchain>=0.1.0
    - langchain-community>=0.0.20
    - langchain-huggingface>=0.0.6
    - langgraph>=0.0.40
    - langsmith>=0.1.0
    - faiss-cpu>=1.7.4
    - sentence-transformers>=2.2.2
    - pypdf>=3.15.1
    - pytest>=7.0.0
    - black>=23.0.0
    - flake8>=5.0.0